"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Project={id?:string;name:string};
type Drawing={id:string;project_id:string;drawing_number:string;title:string;revision:string;status:string;storage_path:string;issue_date:string|null;created_at:string};
type Order={id:string;project_id:string;supplier:string;description:string;order_reference:string|null;quantity:number|null;unit:string|null;unit_cost:number|null;total_cost:number|null;due_at:string|null;status:string;email_thread_url:string|null;ordered_at:string};
type SafetyForm={id:string;project_id:string;form_type:string;title:string;status:string;assigned_to:string|null;created_at:string};
type Member={id:string;full_name:string;role:string};

function ProjectPicker({projects,value,onChange}:{projects:Project[];value:string;onChange:(id:string)=>void}){
 return <label className="opsField">Job<select value={value} onChange={e=>onChange(e.target.value)}>{projects.map(p=><option key={p.id||p.name} value={p.id||""}>{p.name}</option>)}</select></label>
}
function Empty({children}:{children:string}){return <p className="opsEmpty">{children}</p>}
function money(value:number|null|undefined){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(value||0))}
function date(value:string|null){return value?new Date(value).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"}):"Not set"}
function downloadCalendar(order:Order,projectName:string){
 const start=order.due_at?new Date(order.due_at):new Date(); const end=new Date(start.getTime()+60*60*1000);
 const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");
 const content=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//BuildNerve//Material Orders//EN","BEGIN:VEVENT",`UID:${order.id}@buildnerve`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${order.description} delivery`,`DESCRIPTION:${order.supplier} · ${projectName} · ${order.order_reference||"No reference"}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");
 const url=URL.createObjectURL(new Blob([content],{type:"text/calendar"})); const anchor=document.createElement("a");anchor.href=url;anchor.download=`${order.description.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-delivery.ics`;anchor.click();URL.revokeObjectURL(url);
}

export function DrawingRegister({projects}:{projects:Project[]}){
 const [projectId,setProjectId]=useState(""); const [rows,setRows]=useState<Drawing[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!projectId&&projects[0]?.id)setProjectId(projects[0].id)},[projects,projectId]);
 async function load(){if(!projectId)return;const s=createClient();if(!s)return;const {data,error}=await s.from("drawings").select("*").eq("project_id",projectId).order("created_at",{ascending:false});setRows((data||[]) as Drawing[]);if(error)setMessage(error.message)}
 useEffect(()=>{load()},[projectId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!projectId)return;setBusy(true);setMessage("");const form=new FormData(e.currentTarget);const file=form.get("file") as File;const s=createClient();if(!s){setBusy(false);return}const {data:{user}}=await s.auth.getUser();const org=(await s.from("profiles").select("organisation_id").eq("id",user?.id||"").single()).data?.organisation_id;const path=`${org}/${projectId}/drawings/${crypto.randomUUID()}-${file.name}`;const upload=await s.storage.from("project-documents").upload(path,file);if(upload.error){setMessage(upload.error.message);setBusy(false);return}const insert=await s.from("drawings").insert({organisation_id:org,project_id:projectId,drawing_number:String(form.get("number")),title:String(form.get("title")),revision:String(form.get("revision")||"P01"),status:"current",storage_path:path,issue_date:String(form.get("issueDate")||"")||null,uploaded_by:user?.id});setMessage(insert.error?insert.error.message:"Drawing uploaded and added to the job register.");if(!insert.error){e.currentTarget.reset();await load()}setBusy(false)}
 return <section className="opsGrid"><div className="card"><div className="cardHead"><div><h3>Job drawing register</h3><p>Every drawing and revision stays attached to the selected job.</p></div></div><ProjectPicker projects={projects} value={projectId} onChange={setProjectId}/>{rows.length===0?<Empty>No drawings uploaded for this job yet.</Empty>:<div className="tableWrap"><table><thead><tr><th>Drawing</th><th>Title</th><th>Rev</th><th>Status</th><th>Issued</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.drawing_number}</td><td>{r.title}</td><td>{r.revision}</td><td>{r.status}</td><td>{r.issue_date?new Date(r.issue_date).toLocaleDateString("en-GB"):"—"}</td></tr>)}</tbody></table></div>}</div><div className="card"><div className="cardHead"><div><h3>Upload drawing</h3><p>PDFs and drawing files are held in private job storage.</p></div></div><form className="opsForm" onSubmit={submit}><label>Drawing number<input name="number" required placeholder="C-101"/></label><label>Title<input name="title" required placeholder="Drainage layout"/></label><div className="opsPair"><label>Revision<input name="revision" defaultValue="P01"/></label><label>Issue date<input name="issueDate" type="date"/></label></div><label>Drawing file<input name="file" type="file" required/></label><button disabled={busy}>{busy?"Uploading…":"Upload to job"}</button></form>{message&&<p className="opsMessage">{message}</p>}</div></section>
}

export function MaterialWorkspace({projects}:{projects:Project[]}){
 const [projectId,setProjectId]=useState("");const [rows,setRows]=useState<Order[]>([]);const [message,setMessage]=useState("");const [showForm,setShowForm]=useState(false);
 useEffect(()=>{if(!projectId&&projects[0]?.id)setProjectId(projects[0].id)},[projects,projectId]);
 async function load(){if(!projectId)return;const s=createClient();if(!s)return;const {data,error}=await s.from("material_orders").select("*").eq("project_id",projectId).order("due_at");setRows((data||[]) as Order[]);if(error)setMessage(error.message)}useEffect(()=>{load()},[projectId]);
 const months=useMemo(()=>{const result=new Map<string,number>();rows.filter(r=>r.status!=="cancelled").forEach(r=>{const key=new Date(r.ordered_at).toLocaleDateString("en-GB",{month:"long",year:"numeric"});result.set(key,(result.get(key)||0)+Number(r.total_cost||0))});return [...result]},[rows]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const s=createClient();if(!s)return;const {data:{user}}=await s.auth.getUser();const org=(await s.from("profiles").select("organisation_id").eq("id",user?.id||"").single()).data?.organisation_id;const {error}=await s.from("material_orders").insert({organisation_id:org,project_id:projectId,supplier:String(f.get("supplier")),description:String(f.get("description")),order_reference:String(f.get("reference")||"")||null,quantity:Number(f.get("quantity")||0),unit:String(f.get("unit")||"item"),unit_cost:Number(f.get("unitCost")||0),due_at:String(f.get("dueAt")||"")||null,status:"ordered",email_thread_url:String(f.get("emailLink")||"")||null,created_by:user?.id});setMessage(error?error.message:"Material order added to the live job schedule.");if(!error){e.currentTarget.reset();setShowForm(false);load()}}
 const projectName=projects.find(p=>p.id===projectId)?.name||"Job";
 return <section><div className="opsToolbar"><ProjectPicker projects={projects} value={projectId} onChange={setProjectId}/><button onClick={()=>setShowForm(v=>!v)}>{showForm?"Close":"＋ Add material order"}</button></div>{showForm&&<div className="card opsInset"><form className="opsForm" onSubmit={submit}><div className="opsPair"><label>Supplier<input name="supplier" required/></label><label>Order reference<input name="reference"/></label></div><label>Material / description<input name="description" required/></label><div className="opsTriple"><label>Quantity<input name="quantity" type="number" step="0.001" required/></label><label>Unit<input name="unit" placeholder="tonnes"/></label><label>Unit cost (£)<input name="unitCost" type="number" step="0.01" required/></label></div><label>Delivery due<input name="dueAt" type="datetime-local"/></label><label>Live email link<input name="emailLink" type="url" placeholder="https://outlook.office.com/…"/></label><button>Add order</button></form></div>}<div className="metrics opsMetrics">{months.length?months.map(([month,value])=><div className="metricBox" key={month}><span>{month} material value</span><strong>{money(value)}</strong><small>Ordered CVR cost</small></div>):<div className="metricBox"><span>Monthly material value</span><strong>£0.00</strong><small>No orders yet</small></div>}</div><div className="card"><div className="cardHead"><div><h3>Live material orders</h3><p>Supplier correspondence, delivery commitments and CVR value in one job record.</p></div></div>{rows.length===0?<Empty>No material orders for this job yet.</Empty>:<div className="tableWrap"><table><thead><tr><th>Material</th><th>Supplier</th><th>Due</th><th>Value</th><th>Status</th><th>Links</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.description}<small className="opsSub">{r.order_reference||"No reference"}</small></td><td>{r.supplier}</td><td>{date(r.due_at)}</td><td>{money(r.total_cost)}</td><td>{r.status}</td><td className="opsActions">{r.email_thread_url&&<a href={r.email_thread_url} target="_blank" rel="noreferrer">Email</a>}<button onClick={()=>downloadCalendar(r,projectName)}>Calendar</button></td></tr>)}</tbody></table></div>}{message&&<p className="opsMessage">{message}</p>}</div></section>
}

export function SafetyWorkspace({projects}:{projects:Project[]}){
 const [projectId,setProjectId]=useState("");const [rows,setRows]=useState<SafetyForm[]>([]);const [message,setMessage]=useState("");
 useEffect(()=>{if(!projectId&&projects[0]?.id)setProjectId(projects[0].id)},[projects,projectId]);async function load(){if(!projectId)return;const s=createClient();if(!s)return;const {data,error}=await s.from("safety_forms").select("*").eq("project_id",projectId).order("created_at",{ascending:false});setRows((data||[]) as SafetyForm[]);if(error)setMessage(error.message)}useEffect(()=>{load()},[projectId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const s=createClient();if(!s)return;const {data:{user}}=await s.auth.getUser();const org=(await s.from("profiles").select("organisation_id").eq("id",user?.id||"").single()).data?.organisation_id;const {error}=await s.from("safety_forms").insert({organisation_id:org,project_id:projectId,form_type:String(f.get("type")),title:String(f.get("title")),status:"draft",form_data:{notes:String(f.get("notes")||"")},created_by:user?.id});setMessage(error?error.message:"Safety form saved as a draft for this job.");if(!error){e.currentTarget.reset();load()}}
 return <section className="opsGrid"><div className="card"><div className="cardHead"><div><h3>Health & safety forms</h3><p>Job-specific RAMS, briefings, inspections and permits.</p></div></div><ProjectPicker projects={projects} value={projectId} onChange={setProjectId}/>{rows.length===0?<Empty>No safety forms for this job yet.</Empty>:<div className="tableWrap"><table><thead><tr><th>Form</th><th>Type</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.form_type}</td><td>{r.status}</td><td>{new Date(r.created_at).toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div>}</div><div className="card"><div className="cardHead"><div><h3>Create safety form</h3><p>Authorisation and approval remain with designated people.</p></div></div><form className="opsForm" onSubmit={submit}><label>Form type<select name="type"><option>RAMS review</option><option>Daily briefing</option><option>Excavation permit</option><option>Plant inspection</option><option>Near miss</option><option>Site inspection</option></select></label><label>Title<input name="title" required placeholder="Road 3 excavation briefing"/></label><label>Notes<textarea name="notes" rows={5}/></label><button>Create draft form</button></form>{message&&<p className="opsMessage">{message}</p>}</div></section>
}

export function TargetedUpdates({projects}:{projects:Project[]}){
 const [projectId,setProjectId]=useState("");const [members,setMembers]=useState<Member[]>([]);const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState("");
 useEffect(()=>{if(!projectId&&projects[0]?.id)setProjectId(projects[0].id)},[projects,projectId]);useEffect(()=>{(async()=>{const s=createClient();if(!s)return;const {data}=await s.from("profiles").select("id,full_name,role").order("full_name");setMembers((data||[]) as Member[])})()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected.length){setMessage("Select at least one relevant person.");return}const f=new FormData(e.currentTarget);const s=createClient();if(!s)return;const {data:{user}}=await s.auth.getUser();const org=(await s.from("profiles").select("organisation_id").eq("id",user?.id||"").single()).data?.organisation_id;const {data:update,error}=await s.from("targeted_updates").insert({organisation_id:org,project_id:projectId||null,title:String(f.get("title")),body:String(f.get("body")||""),category:String(f.get("category")),created_by:user?.id}).select("id").single();if(error||!update){setMessage(error?.message||"Update could not be created.");return}const recipients=await s.from("targeted_update_recipients").insert(selected.map(recipient_id=>({update_id:update.id,recipient_id})));setMessage(recipients.error?recipients.error.message:`Update shared with ${selected.length} relevant ${selected.length===1?"person":"people"}.`);if(!recipients.error){e.currentTarget.reset();setSelected([])}}
 return <section className="opsGrid"><div className="card"><div className="cardHead"><div><h3>Targeted project update</h3><p>Send information only to the people who need it.</p></div></div><form className="opsForm" onSubmit={submit}><ProjectPicker projects={projects} value={projectId} onChange={setProjectId}/><label>Category<select name="category"><option value="general">General</option><option value="programme">Programme</option><option value="commercial">Commercial</option><option value="safety">Safety</option><option value="drawing">Drawing revision</option><option value="delivery">Delivery</option></select></label><label>Title<input name="title" required/></label><label>Update<textarea name="body" required rows={6}/></label><button>Share with selected people</button></form>{message&&<p className="opsMessage">{message}</p>}</div><div className="card"><div className="cardHead"><div><h3>Relevant people</h3><p>Recipients are explicit, auditable and job-aware.</p></div></div><div className="recipientList">{members.map(m=><label key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id))}/><span><b>{m.full_name}</b><small>{m.role.replaceAll("_"," ")}</small></span></label>)}</div></div></section>
}
